### ISSUE TITLE
Crashes upon succes video views

### ISSUE THREAD

**Issue by John-Birdflu** [retropassdev/RetroPass#41]
Seems to crash the app when several videos are viewed in succession.

**Comment by retropassdev** [comment]
As discussed, this seems to be connected to the size of the videos. High quality game videos might take to much memory resources and combined with a huge library of games and preloaded thumbnails, it might be just enough to crash the app. Xbox dev mode allows "only" 1GB of memory per app. This is plenty for regular apps, but for a frontend where there's a lot of dynamic loading and preloading, it might be too much. 

Also as John mentioned, replacing videos with lower quality videos fixed the issue. However, if you have a huge library, even just browsing through platforms might eventually crash the app due to a large number of preloaded thumbnails.

Retropass does not do any kind of memory management, since it's kind of an edge case, but might look into that in the future.

**Comment by retropassdev** [comment]
Closing for now.
